---
- hosts: localhost
  become: yes
  vars_files:
    - ./vars/default.yml
  roles:
    - { role: geerlingguy.docker, docker_version: 20.10.12 }
    - { role: andrewrothstein.kind, kind_ver: v0.11.1 }


