apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - box.local
        - argo.box.local
        - test.box.local
      port:
        name: http
        number: 80
        protocol: HTTP