---
- name: Install istio tools
  hosts: vagrantbox
  become: yes
  tags:
    - istio

  vars_files:
    - ../vars.yml

  vars:
    - istio_namespace: istio-system
    - istio_ingress_namespace: istio-ingress

  roles:
    - { role: andrewrothstein.kubernetes-helm, kubernetes_helm_ver: v3.7.2 }

  tasks:
    - name: Configure Helm Repo
      command: "{{ bin_dir }}/helm repo add istio https://istio-release.storage.googleapis.com/charts"

    - name: Helm Repo Update
      command: "{{ bin_dir }}/helm repo update"

    - name: Create istio namespace
      command: "{{ kubectl }}  create namespace {{ istio_namespace }}"
      ignore_errors: yes

    - name: Install istio base chart
      command: "{{ helm }} install istio-base istio/base -n {{ istio_namespace }}"
      ignore_errors: yes

    - name: Helm install istiod
      command: "{{ helm }} install istiod istio/istiod -n {{ istio_namespace }} --wait"
      ignore_errors: yes

    - name: Create istio ingressgateway namespace
      command: "{{ kubectl }}  create namespace {{ istio_ingress_namespace }}"
      ignore_errors: yes

    - name: Istio inject ingress gateway namespace
      command: "{{ kubectl }}  label namespace {{ istio_ingress_namespace }} istio-injection=enabled"
      ignore_errors: yes

    - name: Helm install ingress gateway
      command: "{{ helm }} install {{ istio_ingress_namespace }} istio/gateway -n {{ istio_ingress_namespace }} --wait"
      ignore_errors: yes
