---
- name: Install istio tools
  hosts: vagrantbox
  become: yes
  tags:
    - istio

  vars_files:
    - ../vars.yml

  vars:
    - istio_namespace: istio-system

  roles:
    - { role: andrewrothstein.istio, istio_ver: 1.12.1 }

  tasks:
    - name: Install istio operator
      command: "{{ istioctl }} operator init"

    - name: Upload istio operator demo
      copy:
        src: ./istio-operator-demo.yml
        dest: /tmp/istio-operator-demo.yml

    - name: Apply istio operator demo
      command: "{{ kubectl }} -n {{ istio_namespace }} apply -f /tmp/istio-operator-demo.yml"

    - name: Pause for 1 minute
      pause:
        minutes: 1

    - name: Add externalIP to ingress-gateway
      shell: "{{ kubectl }} --namespace {{ istio_namespace }} patch svc istio-ingressgateway -n istio-system -p '{\"spec\": {\"type\": \"LoadBalancer\", \"externalIPs\":[\"55.55.55.5\"]}}'"

    - name: Upload cluster ingress gateway
      copy:
        src: ./cluster-gateway.yml
        dest: /tmp/cluster-gateway.yml

    - name: Apply cluster-gateway.yml
      command: "{{ kubectl }} -n {{ istio_namespace }} apply -f  /tmp/cluster-gateway.yml"

    - name: Upload ingressgateway service
      copy:
        src: ./cluster-gateway-svc.yml
        dest: /tmp/cluster-gateway-svc.yml

    - name: Apply ingressgateway service
      command: "{{ kubectl }} -n {{ istio_namespace }} apply -f  /tmp/cluster-gateway-svc.yml"
