---
- name: K8s Setup
  hosts: localhost
  become: yes
  tags:
    - k8s

  vars_files:
    - ../vars.yml

  vars:
    k8s_version: v1.21.1

  tasks:
    - name: Copy kind-config.yml
      copy:
        src: ./manifest-kind-config.yml
        dest: "{{ home_dir }}/kind-config.yml"

    - name: Get existing Cluster
      command: "{{ bin_dir }}/kind get clusters"
      register: existing_cluster

    - name: Create K8s Cluster
      command: |
        "{{ bin_dir }}"/kind create cluster 
        --name "{{ cluster_name }}" 
        --config "{{ home_dir }}"/kind-config.yml 
        --kubeconfig "{{ home_dir }}"/.kube/config
        --image kindest/node:"{{ k8s_version }}" 
        --wait 5m
      when: existing_cluster.stderr == "No kind clusters found."

    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ k8s_version }}/bin/linux/amd64/kubectl"
        dest: "{{ bin_dir }}/kubectl"
        mode: 0755
        owner: "{{ os_user }}"

    - name: Get all pods
      command: "{{ bin_dir }}/kubectl get pods -A --kubeconfig {{ kube_config }}"
      register: get_pods
    - debug: msg="{{ get_pods.stdout.split('\n') }}"
