---
- name: Install argo cd
  hosts: single_node_k8s
  become: yes
  tags:
    - argo

  vars_files:
    - ../vars.yml

  vars:
    - argocd_namespace: argocd
    - argocd_manifest_filename: manifest-argocd_v2.2.5.yml
    - temp_argocd_manifest_filename: "/tmp/{{ argocd_manifest_filename }}"

  roles:
    - { role: andrewrothstein.kubernetes-helm, kubernetes_helm_ver: v3.7.2 }

  tasks:
    - name: Upload argocd controller manifest
      copy:
        src: "./{{ argocd_manifest_filename }}"
        dest: "{{ temp_argocd_manifest_filename }}"

    - name: Install argocd
      command: "{{ kubectl }} apply -n {{ argocd_namespace }} -f {{ temp_argocd_manifest_filename }}"

    - name: Wait for argocd-server rollout
      shell: "{{ kubectl }} --namespace {{ argocd_namespace }} rollout status deployment argocd-server "
      register: argocd_pods_ready
    - debug: msg="{{ argocd_pods_ready.stdout.split('\n') }}"

    - name: Retrieve default 'admin' password
      command: "{{ kubectl }} -n {{ argocd_namespace }} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}'"
      register: argocd_base64_admin_password
    - debug: msg="{{ argocd_base64_admin_password.stdout | b64decode }}"

    - name: Upload argocd istio virtual service - local
      copy:
        src: ./manifest-istio-virtualservice-local.yml
        dest: /tmp/manifest-istio-virtualservice.yml
      when: vm is match("local")

    - name: Upload argocd istio virtual service - remote
      copy:
        src: ./manifest-istio-virtualservice-remote.yml
        dest: /tmp/manifest-istio-virtualservice.yml
      when: vm is match("remote")


    - name: Apply virtual service
      command: "{{ kubectl }} apply -f /tmp/manifest-istio-virtualservice.yml"

    - name: Upload projects env project
      copy:
        src: ./manifest-argo-envs.yml
        dest: /tmp/manifest-argo-envs.yml

    - name: Apply argo project/env structure
      command: "{{ kubectl }} apply -f /tmp/manifest-argo-envs.yml"

