---
- name: Install argo cd
  hosts: vagrantbox
  become: yes
  tags:
    - argocd

  vars_files:
    - ../vars.yml

  vars:
    - argocd_namespace: argocd
    - argocd_manifest_filename: manifest-argocd_v2.2.5.yml
    - temp_argocd_manifest_filename: "/tmp/{{ argocd_manifest_filename }}"

  tasks:
    - name: Create argocd namespace
      command: "{{ kubectl }}  create namespace {{ argocd_namespace }}"
      ignore_errors: yes

    - name: Upload argocd controller manifest
      copy:
        src: "./{{ argocd_manifest_filename }}"
        dest: "{{ temp_argocd_manifest_filename }}"

    - name: Install argocd
      command: "{{ kubectl }} apply -n {{ argocd_namespace }} -f {{ temp_argocd_manifest_filename }}"

    - name: Wait for argocd pods to be ready
      shell: "{{ kubectl }} wait --namespace=kube-system --for=condition=Ready pods --selector tier=control-plane --timeout=600s"
      register: argocd_pods_ready
    - debug: msg="{{ argocd_pods_ready.stdout.split('\n') }}"

    - name: Retrieve default 'admin' password
      command: "{{ kubectl }} -n {{ argocd_namespace }} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}'"
      register: argocd_base64_admin_password
    - debug: msg="{{ argocd_base64_admin_password.stdout | b64decode }}"
