apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
spec:
  gateways:
    - istio-system/ingress-gateway
  hosts:
    - 192.53.173.177
  http:
    - match:
        - uri:
            prefix: /argo
      route:
        - destination:
            host: argocd-server
            port:
              number: 443

